var CWPDFReaderMode={Chrome:1,Library:2,Publisher:3,Webimporter:4,Drive:5,Firefox:6,LibraryDesktop:7,OpenDrive:8},publishersList={colwiz:{name:"colwiz",appIds:{stage:null,production:null},logoUrl:"/images/webpdf/logo/logo.png",pubModeBtnsTxt:{view:"View & annotate PDF",add:"Add to colwiz Library",viewHover:"Read, annotate and save this article using the colwiz Interactive PDF Reader",addHover:"Save this article to your colwiz library to read and reference anywhere"},readerOptions:{sideBarVisible:!1,
tools:{dragPage:!0,textSelection:!0,drawHighlight:!0,eraser:!0,pencil:!0,rectangle:!0,ellipse:!0,arrow:!0,line:!0,comments:!0,download:!0},fullScreenMode:!0,searchBarVisible:!0,addToLibraryShow:!0,referenceTabShow:!1,shareTabShow:!1,citeTabShow:!1,readerSamePage:!0,showClosedAccessmessage:!0},id:"colwiz",buttonStyle:"default",showAddButton:!1}};if("undefined"!=typeof CWPDFReaderConfig)var readerModeTmp=CWPDFReaderConfig.readerMode;
var CWPDFReaderConfig={readerMode:"undefined"!=typeof CWApiHandler?CWApiHandler.injectedConfig.readerMode: CWPDFReaderMode.Publisher,sentryDomain:"www.colwiz.com",importerDomain:"webpdf",docsPluginEnable:!0,debug:false,publicFace:"public",cwURL:"https://www.colwiz.com",staticDomainURL:"https://cdn.colwiz.com/static",parser:"",domain:"royalsocietypublishing",piwikSiteId: 2,extensionSpecificFiles:{readerSource:"../js/main/04a_pdfreader_chrome.js?1379054322837",readerStyleSource:"../css/webpdf/reader_chrome.css?1379054322837"},
FirefoxSpecificFiles:{readerSource:"resource://jid1-2z9j1M3WgqkBZwww-at-jetpack/colwizwebimporter/data/js/main/04a_pdfreader_firefox.js?1379054322837",readerStyleSource:"resource://jid1-2z9j1M3WgqkBZwww-at-jetpack/colwizwebimporter/data/css/reader_chrome.css?1379054322837"},pubModeBtnsTxt:{view:"View & annotate PDF",add:"Add to colwiz Library",viewHover:"Read, annotate and save this article using the colwiz Interactive PDF Reader",addHover:"Save this article to your colwiz library to read and reference anywhere"},
extModeBtnsTxt:{view:"Read & annotate PDF",add:"Add to colwiz"},isCoreMode:function(){return CWPDFReaderConfig.readerMode===CWPDFReaderMode.Library||CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive},isDesktopMode:function(){return CWPDFReaderConfig.readerMode===CWPDFReaderMode.LibraryDesktop||CWPDFReaderConfig.readerMode===CWPDFReaderMode.OpenDrive},checkReaderMode:function(a){var b;CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive?b="drive":CWPDFReaderConfig.readerMode===CWPDFReaderMode.Library?
b="library":CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?b="chrome":CWPDFReaderConfig.readerMode===CWPDFReaderMode.Publisher?b="publisher":CWPDFReaderConfig.readerMode===CWPDFReaderMode.Firefox?b="firefox":CWPDFReaderConfig.readerMode===CWPDFReaderMode.LibraryDesktop?b="librarydesktop":CWPDFReaderConfig.readerMode===CWPDFReaderMode.OpenDrive&&(b="opendrive");return a?b===a:b},setPublisher:function(a){publisher.appId=a}};"undefined"!==typeof readerModeTmp&&(CWPDFReaderConfig.readerMode=readerModeTmp);
0<=location.href.indexOf("app?x=/pub/reader")&&(CWPDFReaderConfig.readerMode=0<=location.href.indexOf("et=28")?CWPDFReaderMode.Library:CWPDFReaderMode.Drive,CWPDFReaderConfig.readerMode===CWPDFReaderMode.Library&&(publishersList.colwiz.readerOptions.referenceTabShow=!0));if(CWPDFReaderConfig.isCoreMode()||CWPDFReaderConfig.isDesktopMode())CWPDFReaderConfig.cwURL=location.protocol+"//"+location.host;
if(CWPDFReaderConfig.checkReaderMode("publisher")){var colwizOptions;try{if(colwizOptions=window.parent.colwizOptions)CWPDFReaderConfig.setPublisher(colwizOptions.appId),publisher&&(CWPDFReaderConfig.pubModeBtnsTxt.view=publisher.pubModeBtnsTxt.view,CWPDFReaderConfig.pubModeBtnsTxt.add=publisher.pubModeBtnsTxt.add,CWPDFReaderConfig.pubModeBtnsTxt.viewHover=publisher.pubModeBtnsTxt.viewHover,CWPDFReaderConfig.pubModeBtnsTxt.addHover=publisher.pubModeBtnsTxt.addHover)}catch(e$$6){publisher=publishersList.colwiz}}else publisher=
publishersList.colwiz,CWPDFReaderConfig.isCoreMode()?publisher.readerOptions.addToLibraryShow=!1:CWPDFReaderConfig.isDesktopMode()&&(publisher.readerOptions.readerSamePage=!1,publisher.readerOptions.hideReaderLogo=!0,publisher.readerOptions.hideDownloadButton=!0,publisher.readerOptions.hideReaderAvater=!0,publisher.readerOptions.addToLibraryShow=!1);
function CWMetaData(a){this.identifier=a.identifier?a.identifier:"";this.identifierType=a.identifierType?a.identifierType:"";this.pdfLink=a.pdfLink?a.pdfLink:"";this.pubLink=a.pubLink?a.pubLink:"";this.refLink=a.refLink?a.refLink:"";this.title=a.title?a.title:"";this.authors=a.authors?a.authors:"";this.index=a.index?a.index:0;this.psp=a.psp?a.psp:0;this.dataUrl=a.dataUrl?a.dataUrl:"";this.data=a.data?a.data:"";this.type=a.type?a.type:"";this.issn=a.issn?a.issn:"";this.journal=a.journal?a.journal:
"";this.publisher=a.publisher?a.publisher:"";this.year=a.year?a.year:"";this.openaccess=a.openaccess?a.openaccess:!1;this.listingPage=a.listingPage?a.listingPage:!1;this.keywords=a.keywords?a.keywords:"";this.affiliation=a.affiliation?a.affiliation:"";this.otherInfo=a.otherInfo?a.otherInfo:"";this.domain=CWPDFReaderConfig.importerDomain}var isMobileDevice=function(){return"undefined"!==typeof window.orientation};
