var CWUtils={isIframe:window!==window.parent,bParserTest:!1,browser:{adobeAir:!1,ie:!1,ie9:!1,ie8:!1,ie7:!1,ie6:!1,chrome:!1,firefox:!1,opera:!1,safari:!1},checkBrowser:function(){try{var a=navigator.userAgent.toLowerCase();0<=a.indexOf("adobeair")?CWUtils.adobeAir=!0:0<=a.indexOf("firefox")?CWUtils.firefox=!0:0<=a.indexOf("chrome")?CWUtils.chrome=!0:0<=a.indexOf("safari")?CWUtils.safari=!0:0<=a.indexOf("opera")?CWUtils.opera=!0:0<=a.indexOf("msie")&&(CWUtils.ie=!0,0<=a.indexOf("msie 9.0")?CWUtils.ie9=
!0:0<=a.indexOf("msie 8.0")?CWUtils.ie8=!0:0<=a.indexOf("msie 7.0")?CWUtils.ie7=!0:0<=a.indexOf("msie 6.0")&&(CWUtils.ie6=!0))}catch(b){CWUtils.log("Exception: CWUtils.checkBrowser"),CWUtils.log(b)}},isValidURL:function(a){return/(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/.test(a)?!0:!1},getPageUrl:function(){return window.parent.location.href},getPageDomain:function(){var a=window.parent.location;return a.protocol+"//"+a.host},getDomainFromURL:function(a){a=
a.replace(/^(.*\/\/)(.*?)(\/.*)$/,"$2");var b=/(.*?)(\w+)(\.[a-z]{2,3})(\.[a-z]{2})?$/;a.replace(b,"$1").replace(/\./g,"");return a=a.replace(b,"$2")},getPagePathname:function(){return window.parent.location.pathname},iframeCwZ:function(a){return CWUtils.bParserTest?CwZ(a):CwZ(window.parent.document).find(a)},getQueryParam:function(a,b){void 0==b&&(b=location.search);a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(b);return null==c?"":decodeURIComponent(c[1].replace(/\+/g,
" "))},getFileTitle:function(a){var b=a.pdfLink,c=b.indexOf("#"),d=b.indexOf("?"),c=Math.min(0<c?c:b.length,0<d?d:b.length),b=b.substring(b.lastIndexOf("/",c)+1,c),c="";""!=a.identifier&&("number"==typeof a.identifier&&(a.identifier=a.identifier.toString()),c=a.identifier.replace(/[\\\/:\*\?\"<>|]/g,""));a="";a=0<=c.indexOf(b)?c:c+"_"+b;180<a.length&&(a=a.substr(0,180));return 0<=a.toLowerCase().indexOf(".pdf")?a:a+".pdf"},ajax:{post:function(a,b,c,d){void 0===c&&(c=function(){});void 0===d&&(d=function(){});
void 0===b&&(b={});CwZ.ajax({url:a,type:"POST",dataType:"text",data:b,success:c,error:d})},get:function(a,b,c,d){void 0===c&&(c=function(){});void 0===d&&(d=function(){});void 0===b&&(b={});CwZ.ajax({url:a,type:"GET",dataType:"text",data:b,success:c,error:d})}},updateScrollbar:function(a,b,c){CwZ(a).each(function(){var a=CwZ(this),e=!1;a.is(":visible")||(e=!0,a.show());a.is(".cw-pageContent")&&c&&(padding=20);try{-1!=CwZ(".cw-zoom-menu a.cw-zoom-text").find("i").text().indexOf("Fit Width")?CwZ("#ascrail2000-hr").hide():
CwZ("#ascrail2000-hr").width()<CwZ("#ascrail2000-hr div").width()?CwZ("#ascrail2000-hr").hide():CwZ("#ascrail2000-hr").css("display","")}catch(f){}e&&a.hide();b&&b(a)})},moveScrollbarTo:function(a,b,c,d){void 0==c&&(c=!0);CwZ(a).each(function(){var a=CwZ(this);c?a.animate({scrollTop:b},400):a.scrollTop(parseInt(b));setTimeout(function(){d&&0<d.length&&d.trigger("mouseenter")},1E3)})},moveScrollbarToXY:function(a,b,c){CwZ(a).each(function(){var a=CwZ(this),e=a.scrollTop(),f=a.scrollLeft();a.scrollTop(e+
-1*c,60);a.scrollLeft(f+-1*b,60)})},convertStrToBlob:function(a){var b;try{b=new Blob([a])}catch(c){window.BlobBuilder=window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder,b=new BlobBuilder,b.append(a),b=b.getBlob()}return b},log:function(a){a="object"==typeof a?a.message:a;CWPDFReaderConfig.debug&&(this.ie7&&(this.ie8||this.webkit)?console.log("log:"+a):console.info(a))},trim:function(a){if(null==a||void 0===a)a="";return CwZ.trim(a)},stripTags:function(a){return a=a.replace(/(<([^>]+)>)/ig,
"")},timeDifference:function(a,b,c){void 0==b&&(b="Updated ");void 0==c&&(c="");a=new Date(a);var d=((new Date).getTime()-a.getTime())/1E3,e=Math.round(d/60),f=Math.round(e/60),g=Math.round(f/24),d=Math.round(d),e=Math.round(e),f=Math.round(f),g=Math.round(g);b=0<g?7<g?b+("JanFebMarAprMayJunJulAugSepOctNovDec".substr(3*a.getMonth(),3)+" "+a.getDate()+", "+a.getFullYear()):b+(g+" day"+(1<g?"s":"")+" ago"):0<f?b+(f+" hour"+(1<f?"s":"")+" ago"):0<e?b+(e+" minute"+(1<e?"s":"")+" ago"):10>d?b+"Few secs ago":
b+(d+" sec"+(1<d?"s":"")+" ago");return b+c},Compare:function(a,b){return a<=b+2&&a>=b-2},decompress:function(a){a=a.replace(/\n/g,"");a=a.replace(/ \/ /g,"/");a=atob(a);a=a.split("").map(function(a){return a.charCodeAt(0)});a=(new Zlib.Gunzip(a)).decompress();for(var b="",c=0;c<a.byteLength;c++)b+=String.fromCharCode(a[c]);return b},compress:function(a){a=a.split("").map(function(a){return a.charCodeAt(0)});a=(new Zlib.Gzip(a)).compress();for(var b="",c=0;c<a.byteLength;c++)b+=String.fromCharCode(a[c]);
b=btoa(b);return CWUtils.insertBN(b)},insertBN:function(a){for(var b="";0<a.length;){var c=a.slice(0,76),b=b+c;76===c.length&&(b+="\n");a=a.replace(c,"")}return b},writeCookie:function(a,b,c){if(c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="; expires="+d.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/"},readCookie:function(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,
d.length)}return null},deleteCookie:function(a){createCookie(a,"",-1)}},Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){try{var b="",c,d,e,f,g,h,k,l=0;for(a=Base64._utf8_encode(a);l<a.length;)c=a.charCodeAt(l++),d=a.charCodeAt(l++),e=a.charCodeAt(l++),f=c>>2,g=(c&3)<<4|d>>4,h=(d&15)<<2|e>>6,k=e&63,isNaN(d)?h=k=64:isNaN(e)&&(k=64),b=b+this._keyStr.charAt(f)+this._keyStr.charAt(g)+this._keyStr.charAt(h)+this._keyStr.charAt(k);return b}catch(m){return""}},
decode:function(a){var b="",c,d,e,f,g,h=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");h<a.length;)c=this._keyStr.indexOf(a.charAt(h++)),d=this._keyStr.indexOf(a.charAt(h++)),f=this._keyStr.indexOf(a.charAt(h++)),g=this._keyStr.indexOf(a.charAt(h++)),c=c<<2|d>>4,d=(d&15)<<4|f>>2,e=(f&3)<<6|g,b+=String.fromCharCode(c),64!=f&&(b+=String.fromCharCode(d)),64!=g&&(b+=String.fromCharCode(e));return b=Base64._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=
a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){for(var b="",c=0,d=c1=c2=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|
c3&63),c+=3);return b}};
