var CWComManager={CWIFrameManager:null,init:function(){CWIFrameManager=new IframeManager;CWIFrameManager.setListener(CWComManager.onMessage);CWIFrameManager.tell("iframe-loaded",{view:"mainExt",source:"cwFrame"})},onMessage:function(a){CWUtils.log("com_manager.js CWComManager.onMessage:"+a.message);switch(a.message){case "sendException":CWDataCenter.postMsgToSentry(a.data.error);break;case "postToTracker":CWDataCenter.postToTracker(a.data.action,a.data.metaData);break;case "signoutCallToColwiz":CWDataCenter.signoutCallToColwiz();
break;case "redirectToMyProfile":CWDataCenter.redirectToMyProfile();break;case "polling":CWDataCenter.polling();break;case "loadConfig":CWDataCenter.checkLogin(CWDataCenter.loadConfig);break;case "checkLogin":CWDataCenter.checkLogin(function(){CWIFrameManager.tell("defferredAction",{loggedIn:!0,view:"mainExt",source:"cwFrame"})},function(){CWIFrameManager.tell("defferredAction",{showSignIn:a.data.showSignIn,loggedIn:!1,view:"mainExt",source:"cwFrame"})});break;case "updateUserDOM":CWDataCenter.updateUserDOM();
break;case "findPubsCall":CWDataCenter.findPubs();break;case "getFileId":CWDataCenter.getFileId(!0);break;case "syncData":CWDataCenter.syncData();break;case "saveComments":CWDataCenter.saveComments(a.data.cmtString);break;case "pubSelected":CWDataCenter.pubSelected=a.data.metaData;break;case "createPublication":CWDataCenter.createPublication(a.data.obj,a.data.isFromPage);break;case "addToLibrary":CWDataCenter.addToLibrary(a.data.index);break;case "getUploadParams":CWDataCenter.getUploadParams(a.data);
break;case "uploadSync":CWDataCenter.uploadSync(a.data);break;case "failureHandler":CWDataCenter.failuresHandler(a.data);break;case "setPublisherOptions":CWDataCenter.publisherOptions=a.data.colwizOptions;break;case "resetVariables":CWDataCenter.resetVariables();break;case "isLoginShown":CWDataCenter.isLoginShown=a.data.isLoginShown;break;case "setPageMeta":CWDataCenter.setPageMeta(a.data.hashMeta);break;case "setMetaData":CWDataCenter.setMetaData(a.data.metaData,a.data.index);break;case "getFileBlob":CWPDFReader.getBlob(a.data.url,
a.data.action,a.data.metaData);break;case "processTasks":CWTaskManager.process();break;case "findFile":CWDataCenter.findFile(CWTaskManager.curTask,a.data.bAccess);break;case "removeAllTasks":CWDataCenter.removeAllTasks();break;case "checkPendingTasks":CWDataCenter.checkPendingTasks();break;case "setImporter":CWDataCenter.setImporter();break;case "getRelatedPubs":CWDataCenter.getRelatedPubs(a.data.data);break;case "addRelatedPub":CWDataCenter.addRelatedPub(a.data.eId);break;case "getCSLFile":CWDataCenter.getCSLFile(a.data.path);
break;case "getCSLJson":CWDataCenter.getCSLJson(a.data.url);break;case "getRefsFromServer":CWDataCenter.getRefsFromServer(a.data.url,a.data.metadata);break;case "ajaxCall":CWDataCenter.ajaxCall(a.data.data);case "getAuthors":CWDataCenter.getAuthors(a.data.path,a.data.data,a.data.isPubPage)}},tell:function(a,b,c){b=b||{};var d;"cwFrame"==c?d=CwZ("#cw-colwizFrame")[0]:"pdfFrame"==c&&(d=CwZ("#cw-pdfFrame")[0]);d&&d.contentWindow.postMessage({message:a,data:b},"*")}};
CwZ(document).ready(function(){try{var a=function(){CWPDFReader?CWComManager.init():setTimeout(function(){a()},1E3)};a()}catch(b){CWUtils.log("Com_Manager"+b)}});
var CWPDFReader={showSyncMode:function(){CWIFrameManager.tell("showSyncMode",{view:"mainExt",source:"cwFrame"})},logoutFromReaderCallback:function(){CWIFrameManager.tell("logoutCallback",{view:"mainExt",source:"cwFrame"})},sendJSONToReader:function(a){CWIFrameManager.tell("sendJSONToReader",{jsonData:a,view:"mainExt",source:"cwFrame"})},showAddMode:function(){CWIFrameManager.tell("showAddMode",{view:"mainExt",source:"cwFrame"})},showLoginFrame:function(){CWIFrameManager.tell("showLoginFrame",{view:"mainExt",
source:"cwFrame"})},showProgress:function(a,b,c,d){CWIFrameManager.tell("showProgress",{type:a,message:b,progress:c,index:d,view:"mainExt",source:"cwFrame"})},hideProgress:function(a,b){CWIFrameManager.tell("hideProgress",{timeout:a,index:b,view:"mainExt",source:"cwFrame"})},loadComments:function(a){CWIFrameManager.tell("loadComments",{commentStr:a,view:"mainExt",source:"cwFrame"})},getComments:function(){CWIFrameManager.tell("getComments",{view:"mainExt",source:"cwFrame"})},getBlob:function(a,b,
c){CWIFrameManager.tell("getBlob",{view:"mainExt",source:"cwFrame",url:a,action:b,metaData:c})},getData:function(a){CWIFrameManager.tell("getData",{metadata:a,view:"mainExt",source:"cwFrame"})},setUaC:function(a){},updateUser:function(a){if(!a)CWIFrameManager.tell("updateUser",{userImgURL:"",uName:"",view:"mainExt",source:"cwFrame"});else if(CWPDFReaderConfig.dataImgURL){0>CWPDFReaderConfig.dataImgURL.indexOf("http")&&0>CWPDFReaderConfig.cwURL.indexOf("ro.colwis.org")&&(CWPDFReaderConfig.dataImgURL=
"https:"+CWPDFReaderConfig.dataImgURL);a=CWPDFReaderConfig.dataImgURL+"t/101/"+CWPDFReaderConfig.proId+".jpg?"+Math.floor((new Date).valueOf()/1E3);-1!=CWPDFReaderConfig.cwURL.indexOf("ro.colwis.org")&&(a=CWPDFReaderConfig.cwURL+a);try{CWIFrameManager.tell("updateUser",{pts:CWPDFReaderConfig.pts,userImgURL:a,uName:CWPDFReaderConfig.uName,view:"mainExt",source:"cwFrame"})}catch(b){CWIFrameManager.tell("updateUser",{pts:CWPDFReaderConfig.pts,userImgURL:"",uName:CWPDFReaderConfig.uName,view:"mainExt",
source:"cwFrame"}),CWUtils.log("image doesn't exist")}}},uploadFile:function(a,b,c){CWIFrameManager.tell("uploadFile",{pdfLink:a,index:b,params:c,view:"mainExt",source:"cwFrame"})},postFile:function(a,b){CWIFrameManager.tell("postFile",{url:b,obj:a,view:"mainExt",source:"cwFrame"})},hasPubInLib:function(a,b){CWIFrameManager.tell("hasPubInLib",{bValue:a,index:b,view:"mainExt",source:"cwFrame"})},getMetaData:function(a){CWIFrameManager.tell("getMetaData",{metaData:a,view:"mainExt",source:"cwFrame"})},
setPublicationId:function(a){CWIFrameManager.tell("setPublicationId",{pubId:a,view:"mainExt",source:"cwFrame"})},set_bLogin:function(a){CWIFrameManager.tell("set_bLogin",{bLogin:a,view:"mainExt",source:"cwFrame"})},logConsole:function(a,b,c){CWIFrameManager.tell("logConsole",{strText:a,strHeading:b,bPromptUser:c,view:"mainExt",source:"cwFrame"})},showLogoutBox:function(){CWIFrameManager.tell("showLogoutBox",{view:"mainExt",source:"cwFrame"})},hideSyncingDisplay:function(){CWIFrameManager.tell("hideSyncingDisplay",
{view:"mainExt",source:"cwFrame"})},checkForPDFAccess:function(a){CWIFrameManager.tell("checkForPDFAccess",{pdfLink:a,view:"mainExt",source:"cwFrame"})},setPendingTasks:function(a){CWIFrameManager.tell("setPendingTasks",{value:a,view:"mainExt",source:"cwFrame"})},setRelatedPubs:function(a){CWIFrameManager.tell("setRelatedPubs",{value:a,view:"mainExt",source:"cwFrame"})},addRelatedPubResp:function(a){CWIFrameManager.tell("addRelatedPubResp",{value:a,view:"mainExt",source:"cwFrame"})},cslResponse:function(a){CWIFrameManager.tell("cslResponse",
{response:a,view:"mainExt",source:"cwFrame"})},cslJSONResponse:function(a){CWIFrameManager.tell("cslJSONResponse",{response:a,view:"mainExt",source:"cwFrame"})},serverRefsResponse:function(a,b){a?CWIFrameManager.tell("serverRefsResponse",{resp:a,view:"mainExt",source:"cwFrame",metadata:b}):CWIFrameManager.tell("noRefsFoundOnServer",{resp:a,view:"mainExt",source:"cwFrame",metadata:b})},ajaxCallResp:function(a){CWIFrameManager.tell("ajaxCallResp",{data:a,view:"mainExt",source:"cwFrame"})},sendAuthors:function(a){CWIFrameManager.tell("sendAuthors",
{resp:a,view:"mainExt",source:"cwFrame"})}};
