var CWHtmlStructure={getBody:function(a,b){a=encodeURI(a);b=encodeURI(b);var d="cw-logo";CWPDFReaderConfig.readerMode==CWPDFReaderMode.Publisher&&(d="publisher-logo");var c="display:none;",e="";CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Drive&&(c="",e="display:none;");var f=CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive,g=CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Drive;CwH.partials=
CwH.templates;return(0,CwH.templates.getBody)({smallCanvasClass:"",imageUrl:a,logoClass:d,modeDrive:f,modeNotDriveLibrary:g,fullscreenBtnStyle:c,restoreBtnStyle:e,CWPDFReaderConfig:{cwURL:CWPDFReaderConfig.cwURL},pdfUrl:b})},getCommentBody:function(a){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getCommentBody:window.parent.CwH.templates.getCommentBody)({cmtId:a.cmtId,cmtText:a.cmtText,cmtClass:a.cmtClass,timeDiff:a.timeDiff,cmtPage:a.cmtPage,
minY:a.minY})},getSplashScreen:function(a){CwH.partials=CwH.templates;var b=CwH.templates.getSplash,d=!CWPDFReaderConfig.isCoreMode();return b({classSpec:a,notCoreMode:d,loaderClass:d?"cw-loader":""})},getPopupBody:function(a,b){return(0,CwH.templates.getPopupBody)({getRecHtml:a,contextCont:b})},getDownloadPopup:function(a,b){var d=JSON.parse(JSON.stringify(a));/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})([=]{1,2})?$/.test(d.title)&&(d.title=Base64.decode(d.title));
var c=btoa(d.pdfLink+"@@@0");return(0,CwH.templates.getDownloadPopup)({metaData:d,encodedHash:c,publisherOpt:b})},getReferenceTip:function(a,b){var d=window.parent.CwH.templates.getReferenceTip,c={ref:a};b&&(c.tip=!0);return d(c)},getAuthorSideBarLi:function(a,b){1<a.pubs&&(a.pubsPlus=!0);1<a.coAuthors&&(a.coAuthPlus=!0);1<b?CwZ(".cw-authorTab .numberOfAuthors span").text(b+" Authors"):CwZ(".cw-authorTab .numberOfAuthors span").text(b+" Author");a.nameInitials=function(a){a=a.toUpperCase().split(/[\s.]+/);
var b="";return b=1==a.length?a[0].charAt(0):a[0].charAt(0)+a[a.length-1].charAt(0)}(a.fullName);a.avatarBGColor=function(a){try{var b="#626be0 #e06277 #b467da #e09862 #1abc9c #f44336 #3498db #673ab7 #34495e #8bc24a #27ae60 #2980b9 #8e44ad #6c3244 #f1c40f #2266e6 #e74c3c #50e3c2 #4498ae #f39c12 #2c5e1c #ea1e63 #62b6e0 #484d9c".split(" "),e=" A B C D E F G H I J K L M N O P Q R S T U V W X Y Z".split(" "),f=e.slice();f.shift();var g="";e.forEach(function(e,h){f.forEach(function(f,h){a==e+f&&(g=b[h%
b.length])})});return g}catch(h){return"#000000"}}(a.nameInitials);return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getAuthorSideBarLi:window.parent.CwH.templates.getAuthorSideBarLi)(a)},getAuthorSidebarWidget:function(a,b,d,c,e){return(0,CwH.templates.getAuthorSidebarWidget)({nameInitials:a,avatarBGColor:b,thisAuth:d,pubs:c,co_authors:e})},getHead:function(a,b,d){var c="lib/jquery_ireader.js lib/raven.js lib/blob.js lib/jDialog.js lib/jDialogFunc.js lib/compatibility.js lib/pdf.js lib/svg.min.js lib/svg.filter.js lib/zlib_and_gzip.min.js lib/pdf_find_controller.js lib/tether.js extension/html_structure.js publisher/iframe_pub.js ../extraction/authortooltip/js/00_main.js main/00_config.js main/01_logger.js main/02_cw_codec.js main/03_utilities.js /main/03b_pdfreader.js".split(" "),
e=[];CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?c.push("main/04a_pdfreader_chrome.js"):CWPDFReaderConfig.readerMode===CWPDFReaderMode.Library?c.push("main/04a_pdfreader_library.js"):CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive?c.push("main/04a_pdfreader_drive.js"):CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Publisher&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Webimporter||c.push("main/04a_pdfreader_publisher.js");c.push("main/05_annotations.js");c.push("main/06_page.js");
CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Publisher&&c.push("main/07_datacenter.js");c.push("main/08_textlayer.js");c.push("main/09_comments.js");c.push("main/10_shape.js");CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?e.push("reader_chrome.css"):e.push("reader_web.css");return(0,CwH.templates.getHead)({scripts:c,css:e,jsPath:a,cssPath:b,version:d})},getSignupDialog:function(){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getSignupDialog:
window.parent.CwH.templates.getSignupDialog)({})},getFeedbackForm:function(){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getFeedbackForm:window.parent.CwH.templates.getFeedbackForm)({})},getUserToDD:function(a,b){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getUserToDD:window.parent.CwH.templates.getUserToDD)({uid:a,divText:b})},getCoreDialog:function(){return(CWPDFReaderConfig.isDesktopMode()||
CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getCoreDialog:window.parent.CwH.templates.getCoreDialog)({})},getSupplementLiHtml:function(a,b){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getSupplementLiHtml:window.parent.CwH.templates.getSupplementLiHtml)({key:a,finalFile:b})},insertButtonsOnPage:function(a){if(CWPDFReader.pubSolInjected)return!0;var b="hidden"!=CwZ.trim(a["class"]),d="",c=!1,e=!1,f,g=!1;publisher&&
(c=!!~a["class"].trim().indexOf("-list"),e=!!~a["class"].trim().indexOf("-detail"),f=publisher.buttonStyle,g=(c||e)&&"popup"==f);if(b)if("popup"==f)if(0==CwZ("#preloadCwZSprite").length&&CwZ("body").append('<div id="preloadCwZSprite"></div>'),e)try{return a.buttonCB(a.metaData),!1}catch(h){return!1}else{if(c)try{return a.buttonCB(a.metaData),!1}catch(k){return!1}}else b=!0,d="View & Annotate PDF",e="Add to colwiz",a||(a={pdfUrl:"",index:0,inline:!1,"class":""}),CWPDFReader.colwizOptions&&(b=CWPDFReader.colwizOptions.showAddToColwiz),
c="",CWPDFReaderConfig.readerMode===CWPDFReaderMode.Webimporter&&(c='style="display:none !important"',e=CWPDFReaderConfig.pubModeBtnsTxt,d=e.view,e=e.add),CWPDFReaderConfig.readerMode===CWPDFReaderMode.Publisher&&(a["class"]+=" pub-mode",e=CWPDFReaderConfig.pubModeBtnsTxt,d=e.view,e=e.add),CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome&&(d=CWPDFReaderConfig.extModeBtnsTxt.view),f="",a.inline&&!g&&(f=" cw-inline"),f+=" "+a["class"],g&&(c='style="display:none"'),g=CWHtmlStructure.generateReaderHash(a.pdfUrl,
a.index),d=(0,CwH.templates.getButtons)({classes:f,style:c,generatedHash:g,index:a.index,url:a.pdfUrl,viewBtnTxt:d,hoverBtnText:CWPDFReaderConfig.pubModeBtnsTxt.viewHover,showAddButton:b,addBtnTxt:e,addHoverBtnText:CWPDFReaderConfig.pubModeBtnsTxt.addHover});return d},generateReaderHash:function(a,b,d){a=a+"@@@"+b;d&&(a+="@@@forwarded");return a=Base64.encode(a)},decodeReaderHash:function(a){a=Base64.decode(a).split("@@@");var b=[];b.PDFURL=a[0];b.INDEX=a[1];a[2]&&"forwarded"==a[2]&&(b.FORWARDED=
!0);return b}};
